export const students = [
  {
    id: "1",
    name: "John Smith",
    grade: 88,
    email: "john.smith@example.com",
    date: "2022-11-23",
    address: "123 Maple St.",
    city: "New York",
    country: "USA",
    zip: "10001",
    subject: "Philosophy"
  },
  {
    id: "2",
    name: "Jane Doe",
    grade: 92,
    email: "jane.doe@example.com",
    date: "22-09-2025",
    address: "456 Oak Ave.",
    city: "Los Angeles",
    country: "USA",
    zip: "90001",
    subject: "Physics"
  },
  {
    id: "3",
    name: "Michael Johnson",
    grade: 96,
    email: "michael.johnson@example.com",
    date: "2022-05-23",
    address: "789 Pine Rd.",
    city: "Chicago",
    country: "USA",
    zip: "60601",
    subject: "Chemistry"
  },
  {
    id: "4",
    name: "Emily Davis",
    grade: 85,
    email: "emily.davis@example.com",
    date: "2024-01-20",
    address: "234 Birch Blvd.",
    city: "Houston",
    country: "USA",
    zip: "77001",
    subject: "Biology"
  },
  {
    id: "1",
    name: "John Smith",
    grade: 58,
    email: "john.smith@example.com",
    date:"2022-11-13",
    address: "123 Maple St.",
    city: "New York",
    country: "USA",
    zip: "10001",
    subject: "Philosophy"
  },
  {
    id: "2",
    name: "Jane Doe",
    grade: 92,
    email: "jane.doe@example.com",
    date: "2024-08-14",
    address: "456 Oak Ave.",
    city: "Los Angeles",
    country: "USA",
    zip: "90001",
    subject: "Physics"
  },
  {
    id: "3",
    name: "Michael Johnson",
    grade: 76,
    email: "michael.johnson@example.com",
    date: "2024-04-23",
    address: "789 Pine Rd.",
    city: "Chicago",
    country: "USA",
    zip: "60601",
    subject: "Chemistry"
  },
  {
    id: "4",
    name: "Emily Davis",
    grade: 25,
    email: "emily.davis@example.com",
    date: "2023-11-07",
    address: "234 Birch Blvd.",
    city: "Houston",
    country: "USA",
    zip: "77001",
    subject: "Philosophy"
  },
  {
    id: "5",
    name: "David Wilson",
    grade: 94,
    email: "david.wilson@example.com",
    date: "2024-01-17",
    address: "345 Cedar Ln.",
    city: "Phoenix",
    country: "USA",
    zip: "85001",
    subject: "Computer Science"
  },
  {
    id: "6",
    name: "Sophia Martinez",
    grade: 84,
    email: "sophia.martinez@example.com",
    date: "2022-11-23",
    address: "567 Elm St.",
    city: "San Francisco",
    country: "USA",
    zip: "94101",
    subject: "Mathematics"
  },
  {
    id: "7",
    name: "Daniel Brown",
    grade: 78,
    email: "daniel.brown@example.com",
    date: "2024-06-02",
    address: "678 Willow Dr.",
    city: "Seattle",
    country: "USA",
    zip: "98101",
    subject: "Philosophy"
  },
  {
    id: "7",
    name: "Daniel Brown",
    grade: 60,
    email: "daniel.brown@example.com",
    date: "2024-06-24",
    address: "678 Willow Dr.",
    city: "Seattle",
    country: "USA",
    zip: "98101",
    subject: "Philosophy"
  },
  {
    id: "8",
    name: "Olivia Clark",
    grade: 90,
    email: "olivia.clark@example.com",
    date: "2024-11-02",
    address: "789 Spruce Ct.",
    city: "Miami",
    country: "USA",
    zip: "33101",
    subject: "Philosophy"
  },
  {
    id: "059797100",
    name: "James Miller",
    grade: 81,
    email: "james.miller@example.com",
    date: "2024-06-24",
    address: "890 Aspen Rd.",
    city: "Boston",
    country: "USA",
    zip: "02101",
    subject: "Mathematics"
  },
  {
    id: "212561641",
    name: "Mia Garcia",
    grade: 87,
    email: "mia.garcia@example.com",
    date:"2024-06-17",
    address: "901 Cypress St.",
    city: "Dallas",
    country: "USA",
    zip: "75201",
    subject: "Political Science"
  }  ,
   {
    id: "212561641",
    name: "Mia Garcia",
    grade: 97,
    email: "mia.garcia@example.com",
    date: "2024-02-07",
    address: "901 Cypress St.",
    city: "Dallas",
    country: "USA",
    zip: "75201",
    subject: "Philosophy"
  }
];
